package com.luckyend.generators.metamodel.client;

import java.lang.Class;
import java.lang.String;
import javax.annotation.Generated;

/**
 * Generated Java class that contains name attributes from a Java Bean: com.luckyend.generators.metamodel.client.SampleBean
 * Generated by: Bean Metamodel Generator
 */
@Generated("com.luckyend.generators.metamodel.processors.BeanMetamodelProcessor")
public class SampleBean_BeanModel {

	/**
	 * Field name constant for attribute: attribute2
	 */
	public static final String ATTRIBUTE = "attribute";
	/**
	 * Field name constant for attribute: status
	 */
	public static final String STATUS = "status";
	
    /**
     * Gets the bean class object.
     *
     * @return the bean class
     */
    public static Class<?> getBeanClass() {
        return com.luckyend.generators.metamodel.client.SampleBean.class;
    }

    /**
     * Gets the bean class name.
     *
     * @return the bean class name
     */
    public static String getBeanClassName() {
        return "com.luckyend.generators.metamodel.client.SampleBean";
    }

    /**
     * Returns the list of field names for com.luckyend.generators.metamodel.client.SampleBean bean.
     *
     * @return the list of field names
     */
    public String[] getFieldNames() {
        return new String[] {
            ATTRIBUTE,            STATUS        };
    }
}